module.exports = {
    PAGE_SIZE: 5,

    province: [
        'Blagoevgrad',
        'Burgas',
        'Varna',
        'Veliko Tarnovo',
        'Vidin',
        'Vratsa',
        'Gabrovo',
        'Dobrich',
        'Kardzhali',
        'Kyustendil',
        'Lovech',
        'Montana',
        'Pazardzhik',
        'Pernik',
        'Pleven',
        'Plovdiv',
        'Pazgrad',
        'Ruse',
        'Silistra',
        'Sliven',
        'Smolyan',
        'Sofia',
        'Stara Zagora',
        'Targovishte',
        'Haskovo',
        'Shumen',
        'Yambol',
    ],
    convertNumberToCurrency: (number) =>
        number.toLocaleString('de-DE', {
            style: 'currency',
            currency: 'EUR',
            minimumFractionDigits: 0,
        }),
};
